### ISSUE TITLE
Support for new repository packaging type attribute for Artifactory 4.x

### ISSUE THREAD

**Issue by antoniobeyah** [chef/artifactory-client#56]
With the introduction of Artifactory 4, it is now a requirement that each repository has exactly 1 packaging type, and it cannot be changed after the repository is created with that type.

The default package type is 'generic', which is unsuitable for some (read most) scenarios.

The new element in the rest api (taken from the link below) is:
  - "packageType": "maven" | "gradle" | "ivy" | "sbt" | "nuget" | "gems" | "npm" | "bower" | "debian" | "pypi" | "docker" | "vagrant" | "gitlfs" | "yum" | "generic"

See:
https://www.jfrog.com/confluence/display/RTF/Configuring+Repositories
https://www.jfrog.com/confluence/display/RTF/Repository+Configuration+JSON#RepositoryConfigurationJSON-application/vnd.org.jfrog.artifactory.repositories.LocalRepositoryConfiguration+json

**Comment by antoniobeyah** [comment]
I am willing to perform this work and submit a PR for it but want to make sure no one else is currently working on it.  Is this task on the docket for inclusion somewhere?

**Comment by schisamo** [comment]
@antoniobeyah We have not started on that work yet so a PR would be greatly appreciated.

**Comment by antoniobeyah** [comment]
@schisamo see pr #57

**Comment by robkinyon** [comment]
Can this be closed?
