### ISSUE TITLE
Given an endpoint with a path part, version 2.3.1 tries to access an invalid URI during a GAVC search

### ISSUE THREAD

**Issue by aogail** [chef/artifactory-client#60]
We use artifactory-client in our CI environment, interacting with Artifactory Pro v3.9.4. We noticed that after artifactory-client 2.3.1 was released, our GAVC searches began to fail with a 404 error. This appears to be a result of the attempt to make all requests relative to the original configured endpoint. Based on my reading of the code and the behavior in a debugger, I think it is broken for any case where the Artifactory endpoint is not at the root. In other words, where the endpoint URI has a path part.

Say we have set `Artifactory.endpoint` to `http://artifacts.example.com:8081/artifactory` and execute a GAVC search. In `Artifact.gavc_search`, it makes a GET request to `#{endpoint}/api/search/gavc`. It then uses the response to build URLs for the results. The issue is in building the URLs for the results. At `artifact.rb:106`, the uri from the response is passed to `from_url`. That uri is in the form `#{endpoint}/path/to/artifact`. For example, `http://artifacts.example.com:8081/artifactory/api/storage/libs-sandbox-local/com/example/test/1.0.0/test-1.0.0.txt`.

The issue is in `from_url`. It takes the entire path part of the URI and asks the `client` instance to get it. However, the client already has part of the path in its endpoint: `/artifactory`. It joins its endpoint with the given path at `client.rb:304`. The end result is that the client attempts to request `http://artifacts.example.com:8081/artifactory/artifactory/api/storage/libs-sandbox-local/com/example/test/1.0.0/test-1.0.0.txt`, which does not exist, because the path part of the endpoint got doubled.

**Comment by schisamo** [comment]
@aogail Ahhh that sucks. Feel free to take a stab at a PR. If you don't get to it I'll try to look later this week.

**Comment by schisamo** [comment]
This was fixed by https://github.com/chef/artifactory-client/pull/61. Version 2.3.2 which contains the fix has also been pushed to Rubygems.org:
https://rubygems.org/gems/artifactory/versions/2.3.2
