### ISSUE TITLE
Delete artifact returns false on successful delete

### ISSUE THREAD

**Issue by alan-schwarzenberger** [chef/artifactory-client#82]
Calling artifact.delete, where artifact is a valid artifact returned from a search function, always returns false, even if the artifact was successfully deleted.
Doing the same with CURL shows that on successful deletion we get back 204 (no content) as the success code, compared to getting back 404 (not found) if the artifact does not exist.
Does delete consider 204 to be a success code?

**Comment by ACPPPF** [comment]
I'm having the same problem.  Is this the expected result?

**Comment by alan-schwarzenberger** [comment]
Stale
